### ISSUE TITLE
Constructor not working on inactive tabbed content (display:none)

### ISSUE THREAD

**Issue by davy39** [jppellet/Logic-Circuit-Simulator#11]
Hello,

Many thanks for this tool that is very great !

I'm trying to get it worked inside [mkdocs-material content tabs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/), but the editors are only constructed on tabs that are active on page load. The other tabbed contents ( which are -> display:none ) are still blank when I activate them after page loading.

I'm using same kind of code as in embedding_modulo.html

Is there a way I can force the script to construct the editors even in parts that are not displayed on page load ?

I've very few skills in js and even less in ts...

Thanks for your help !

**Comment by jppellet** [comment]
Can you share with me somehow the resulting full HTML? I'll try to see what the problem is. It's not supposed to always draw when hidden since it uses `requestAnimationFrame` and the browser can decide not to offer an animation frame when hidden, but it's definitely supposed to build and not be blank.

**Comment by davy39** [comment]
Hi, 
Thanks for your help !

[Here](https://davy39.github.io/mkdocs-material-logic-circuit-simulator/) is a demo of what append when using simulators on tabs with mkdocs-material.

You're right, the editor is constructed but content not drawed. I was integrating the tryout mode, that's why it was blank.

Is there any way to trigger drawings when changing tabs ?

**Comment by jppellet** [comment]
I tried fixing it by setting the size and redrawing when first visible ([9bd27f7](https://github.com/jppellet/Logic-Circuit-Simulator/commit/9bd27f7c7ce5c1e9ebbefcec20facb41c728e17a)). Does it work for you?

**Comment by davy39** [comment]
As you can see in previous demo, that's working like a charm !
I'm gonna explore the functionalities of this amazing tool.
Thank you so much !
