### ISSUE TITLE
Toggle Dark mode in mkdocs-material

### ISSUE THREAD

**Issue by davy39** [jppellet/Logic-Circuit-Simulator#13]
Hi,
I've been playing around with this tool since my last issue, that's very great !

I've encountered one detail : 

As you would see in this [demo](https://davy39.github.io/mkdocs-material-logic-circuit-simulator/), change of theme is inactive when using with mkdocs.

Could you guide me on a way to trigger change from light to dark mode ?

Thanks for your help.

**Comment by jppellet** [comment]
How is the change of theme enacted by the resulting pages from mkdocs, do you know? Is it JavaScript that sends an event, or possibly only CSS? If you can hook into the JS, you can call `Logic.setDarkMode(<boolean>)` (since c9335d656b51e1b6a941b576aa6dca4c2c2c4a99). But maybe if it's easy enough, we can try to integrate it.

**Comment by davy39** [comment]
It can be [customized](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/?h=), but by default it looks like :  
- light theme is obtain with data-md-color-scheme="default" as html body attribute
- dark theme is obtained when data-md-color-scheme="slate" as html body attribute.

That does the trick :
```js
document.body.setAttribute("data-md-color-scheme", "default") 
//or
document.body.setAttribute("data-md-color-scheme", "slate")
```

The tool for switching for one theme to another seems to come from this form :
```html
<form class="md-header__option" data-md-component="palette">
          <input class="md-option" data-md-color-media="(prefers-color-scheme: light)" data-md-color-scheme="default" data-md-color-primary="red" data-md-color-accent="deep-orange"  aria-label="Passer au mode nuit"  type="radio" name="__palette" id="__palette_1">         
          <input class="md-option" data-md-color-media="(prefers-color-scheme: dark)" data-md-color-scheme="slate" data-md-color-primary="red" data-md-color-accent="deep-orange"  aria-label="Passer au mode jour"  type="radio" name="__palette" id="__palette_2">      
</form>
```

Following your directives, I've tried to execute `Logic.setDarkMode(true)` in my browser console, I got : `Uncaught TypeError: Logic.setDark is not a function`

What am I doing wrong ?

**Comment by jppellet** [comment]
If you get an error about `Logic.setDark`, it means you're not using the right function name, which is `setDarkMode` in `Logic.setDarkMode(true)`. But it may also be that you're hosting your own build which is older than the latest changes I've pushed.

For the rest: do know what piece of code actually does the `document.body.setAttribute("data-md-color-scheme", "slate")`? The good place to insert a call to `setDarkMode` would be right after that.

**Comment by davy39** [comment]
My bad, sorry I didn't realize that your commit was new. Thanks for it !
It's working now, so I'm gonna investigate on how to integrate the simulator as a mkdocs-material extension, supporting theming.
I'll keep you updated if I succeed.
Many thanks for your help and reactivity.

**Comment by jppellet** [comment]
Great! Closing the issue for now, but happy to help if I can adapt things directly in the simulator.

**Comment by davy39** [comment]
I found out that does the trick : 
```js
$(document).ready(function() {
// Check out what theme is set when loading the page
    if ($('body').attr('data-md-color-scheme') === 'slate') {
        Logic.setDarkMode(true);
    };
    if ($('body').attr('data-md-color-scheme') === 'default') {
        Logic.setDarkMode(false);
      };
// Toggle if theme changed
    $('input[data-md-color-media="(prefers-color-scheme: dark)"]').change(function() {
        Logic.setDarkMode(true);
    });
    $('input[data-md-color-media="(prefers-color-scheme: light)"]').change(function() {
        Logic.setDarkMode(false);
    });
  });
```
Maybe something similar could be integrated to your code for those using mkdocs-material ?

**Comment by jppellet** [comment]
Nice job! Since that's specific to `mkdocs`, I don't really think it belongs in the shared common code.

**Comment by davy39** [comment]
That make sense.

Just for those who read this and want to implement the simulator in mkdocs-material, here is the code with vanilla JS, so no need to import jquery. Just add it as an `extra_javascript` in your `mkdocs.yml` 
```js
document.addEventListener('DOMContentLoaded', function() {
  var body = document.body;
  if (body.getAttribute('data-md-color-scheme') === 'slate') {
    Logic.setDarkMode(true);
  } else if (body.getAttribute('data-md-color-scheme') === 'default') {
    Logic.setDarkMode(false);
  }
  var darkInput = document.querySelector('input[data-md-color-media="(prefers-color-scheme: dark)"]');
  var lightInput = document.querySelector('input[data-md-color-media="(prefers-color-scheme: light)"]');
  darkInput.addEventListener('change', function() {
    Logic.setDarkMode(true);
  });
  lightInput.addEventListener('change', function() {
    Logic.setDarkMode(false);
  });
});
```
