### ISSUE TITLE
Markdown extension?

### ISSUE THREAD

**Issue by davy39** [jppellet/Logic-Circuit-Simulator#14]
Hi again !
Is there a chance you already have built the markdown extension that convert the exported markdown block to html code ?

**Comment by jppellet** [comment]
What we have in another project is a Sphinx extension. Maybe it can help?

<https://github.com/edunumsec2/book/blob/master/src/exts/logic.py>

**Comment by davy39** [comment]
Ok, thanks.
I think that I'll stick to web component inclusion for now.
That more than useful enough for a mkdocs usage.
Thanks for your helpfulness and patience.

**Comment by jppellet** [comment]
OK, no problem!

**Comment by davy39** [comment]
Hello,
Just so you know, I've finally integrated your app for a simple usage with mkdocs.
That's here : https://mkdocs-logic.forge.apps.education.fr
Thanks again for your work !

**Comment by jppellet** [comment]
Hey @davy39,

This is really great! Awesome!

How are you following up the the updates I'm going to make? Are there specific things from your fork that we should integrate in the main build for your convenience?

Cheers,
J.-P.

**Comment by davy39** [comment]
Hi, 
For now, I've only worked on the mkdocs extension part, hacking your bundle without modifying its source.
It would be great to add an option to the editor ( <logic-editor pymkdownx ....), then use it in the editor to make the markdown output look like `{.logic}` instead of `{logic}` :
```js
const markdownBlock = ``\`\`\`{${pymkdownx ? '.'}logic}\n:height: ${embedHeight}\n${modeParam}\n${fullJson}\n\`\`\``
```
This way i could automatize bundle built from your sources to include it within pymkdown extension.

Do you think that could be the way to do it ?

**Comment by jppellet** [comment]
Sure, looks good. Can you show me the code modifications that you made?

Would it be acceptable if, in order to enable this, you have to call some global setup method like `Logic.setExportOptions(...)` somewhere?

**Comment by jppellet** [comment]
This was finalized in 793785bd7e4a528e5be3a724c1b8787404ef4e3f.
