### ISSUE TITLE
Le type de porte est un peu trop évident quand on le cache

### ISSUE THREAD

**Issue by joel-terraz** [jppellet/Logic-Circuit-Simulator#16]
Bonjour, j'ai utilisé ce simulateur pour la 1ère fois avec des élèves. Je voulais leur donner un circuit à modifier en cachant les portes logiques et en leur partageant un lien "complet", mais en fait avec un clic droit sur une porte, on ne peut remplacer cette porte que par d'autres, et donc on en déduit tout de suite de quel type de porte il s'agit. Pas certain si c'est une erreur ou si c'est voulu et si mon usage n'était pas prévu.
Merci pour ce bel outil, en revanche !
Cordialement.

**Comment by jppellet** [comment]
Bonjour, peux-tu me partager le lien? En effet, a priori, avec un lien complet, on peut tout éditer. Mais j'imagine que l'exercice n'est pas faisable en partageant un lien où on ne fait que les connexions, c'est ça? J'imagine qu'on pourrait faire en sorte que le changement de type des portes cachées n'est possible qu'en mode admin, est-ce que ça réglerait le problème?

**Comment by joel-terraz** [comment]
Bonjour, [voici un lien qui a ce problème](https://logic.modulo-info.ch/?mode=design&data=N4NwXAbANA9gDgFwM5mACwJYBMCmB1DAJxwGEYAbGQlBQgVxwF8oBjGAWzhgDsdvlUGbgAZUCAJ5wcYAORCZULigDaARgBMwqKoCsOgLpRsYYcyGqxk6XO4KlYNZqjqAzMMPHVzAIbcso4AkpWV8sOxgVFwAWHW0Yj24HdSgXQxg6BDAoqCQ0GAB3AEEkAFVuAGtuAsTaBmYqAKDrKnCVKJdY1QAOAyNE5ViINIywAHYcvKLSiqr8mvomWAzGq1l0hFaHHQgtVVH3IywwLuYqhBXgmTPN5XUnXV6hMABOJczVLVyC4rLK6rBakxmPkiDgVGooEMoMpxl1DMpsr0Yc4oKAMN4HMoXDsoPsoDJ8jJ9PpGPCtM94R8UsTGEA). Je voulais cacher l'état des fils, les portes logiques employées pour faire chercher aux élèves ce qui se passait dans ce circuit. Or avec un clic-droit on ne peut pas attribuer le bon type de porte, parce que... c'est déjà le type de cette porte.

Et alors comme on pouvait changer le type de porte, j'ai pensé que ce serait un bon exercice. Donc si on retire la possibilité, effectivement le problème ne se pose plus, et donc les élèves devraient éventuellement recréer le schéma complet.

**Comment by mubinyuwana** [comment]
Bonjour,
i use your app for view month and i try to run it offline and it works with
little bit modification code , i hope it will be another update
function gate . can it make connection to serial bus or to the mqtt so the
input and output can interact ?

thanks for your app



Pada Sel, 30 Jan 2024 pukul 15.09 Jean-Philippe Pellet <
***@***.***> menulis:

**Comment by mubinyuwana** [comment]
Bonjour, est-il possible de créer une fonction label pour l'entrée et une
fonction label pour la sortie ? afin de réduire l'image des lignes de
connexion entre logiques car dans une logique complexe, l'entrée provient
de la sortie d'une autre logique

Pada Sel, 30 Jan 2024 pukul 15.09 Jean-Philippe Pellet <
***@***.***> menulis:

**Comment by jppellet** [comment]
@joel-terraz Ça devrait être OK maintenant.
@mubinyuwana Je ne comprends pas la demande… Chaque entrée et sortie peut déjà avoir un label. Mais je ferme cette issue et la discussion serait à faire dans une autre issue as cas où c'est toujours pertinent. Merci!

**Comment by mubinyuwana** [comment]
is it possible to link other output to become input for other logic without
draw wire ?
[image: logic link.png]



Pada Rab, 31 Jan 2024 pukul 18.52 Jean-Philippe Pellet <
***@***.***> menulis:

**Comment by jppellet** [comment]
This should be another issue, I've copied this to #17.
