### ISSUE TITLE
Right-clicking on Input Component Unintentionally Changes Its Value

### ISSUE THREAD

**Issue by redelmann** [jppellet/Logic-Circuit-Simulator#19]
When right-clicking on an input component, its value is modified in addition to opening the contextual menu. This behavior can be disruptive, especially when attempting to lock a value.

**Comment by jppellet** [comment]
Good point! Should be fixed in cc0886a4a4cb178cc68e7bf18b63459969db4717, deployed right now. Can you confirm?

**Comment by redelmann** [comment]
That was fast, thanks! Fixed for me!

**Comment by jppellet** [comment]
Awesome :)
