### ISSUE TITLE
Intermediate points on wires not moving when moving multiple elements

### ISSUE THREAD

**Issue by redelmann** [jppellet/Logic-Circuit-Simulator#3]
When selecting multiple elements and moving them, the intermediate points placed on wires, even though they appear to be selected, do not move.

**Comment by redelmann** [comment]
I have a fix here: https://github.com/redelmann/Logic-Circuit-Simulator/commit/20102b2554ebb3e0b97760c8de66b7c96f74cafc

**Comment by jppellet** [comment]
Fixed by you; added corresponding "select all" behavior in 70a3ace931d98091fa8ff247c0ac5cbad5352e36
