### ISSUE TITLE
"aux" folder makes it impossible to clone repo on Windows

### ISSUE THREAD

**Issue by chardetm** [jppellet/Logic-Circuit-Simulator#4]
The "aux" folder at the root makes it impossible to clone on Windows: "aux" is an illegal name for a file or folder on Windows. I am not entirely sure of how the graffle file contained inside of it is used (searching the repository didn't give any results), but changing the name to something else if possible would solve the issue.

**Comment by jppellet** [comment]
Fixed in fb34730f491eb802e0c2b4b379d586f1153bd6ae
