### ISSUE TITLE
Some tooltips show non-localized text

### ISSUE THREAD

**Issue by redelmann** [jppellet/Logic-Circuit-Simulator#5]
The tooltip of some gates (for instance AND, OR and so on) seem not to be using the (apparently already existent) translation for some sentences.

**Comment by redelmann** [comment]
Looking a the code, it happens because `setLang` is called after the global variable S has already been read for some translations. One solution could be to ensure that S is not read beforehand. A simpler solution would be to hardcode the chosen lang (maybe have it as part of compile-time config?).

**Comment by jppellet** [comment]
This has been fixed recently; all UI strings are now (should be…) loaded lazily to avoid this.
