### ISSUE TITLE
Scroll behavior and hovered elements

### ISSUE THREAD

**Issue by redelmann** [jppellet/Logic-Circuit-Simulator#9]
Scrolling the page doesn't trigger the same events as mouse movements do.

This means that, for instance, tooltips continue to be shown if scrolling begins on top of a component. The component also remains highlighted.

I would suggest listening to scroll events and update hovered elements.

Cheers !

**Comment by jppellet** [comment]
Thanks, Romain. This is finally fixed in [ce59547](https://github.com/jppellet/Logic-Circuit-Simulator/commit/ce595473956c88c1feeaf5df390c2e35b5d1f77d).
